### ISSUE TITLE
ClothingRooms do not work

### ISSUE THREAD

**Issue by ADRNALN** [qbcore-framework/qb-clothing#107]
When going to a clothing room that's job based the drawtext appears properly on the left hand side of the screen but when you press `E` an error is thrown client side.

![image](https://user-images.githubusercontent.com/32118783/162263106-5978c7f7-91ab-4a0e-9eca-64bd1271beae.png)
![image](https://user-images.githubusercontent.com/32118783/162263198-f18783cd-992a-411e-a000-c7b97950c958.png)

My config.lua, also tried with the default config
```lua
Config.ClothingRooms = {
    [1] = {requiredJob = 'safr', isGang = false, coords = vector3(300.8037, -597.1525, 43.2840), width = 2, length = 2, cameraLocation = vector4(299.9146, -599.6738, 43.3069, 340.1765)}, -- Pillbox
    [2] = {requiredJob = 'safr', isGang = false, coords = vector3(1686.3308, 3589.7537, 35.6293), width = 3, length = 3, cameraLocation = vector4(1687.1141, 3588.2070, 35.6293, 31.6562)}, -- Sandy
    
    [3] = {requiredJob = 'lspd', isGang = false, coords = vector3(461.1000, -996.5984, 30.6896), width = 3, length = 3, cameraLocation = vector4(463.0370, -996.5944, 30.6896, 88.2276)}, -- Mission Row
    [4] = {requiredJob = 'bcso', isGang = false, coords = vector3(461.1000, -996.5984, 30.6896), width = 3, length = 3, cameraLocation = vector4(463.0370, -996.5944, 30.6896, 88.2276)},
    [5] = {requiredJob = 'sasp', isGang = false, coords = vector3(461.1000, -996.5984, 30.6896), width = 3, length = 3, cameraLocation = vector4(463.2244, -996.7193, 30.6896, 82.3690)},
    
    [6] = {requiredJob = 'lspd', isGang = false, coords = vector3(1841.2963, 3681.1711, 34.1892), width = 3, length = 3, cameraLocation = vector4(1839.7710, 3680.2510, 34.1892, 300.7488)}, -- Sandy SO
    [7] = {requiredJob = 'bcso', isGang = false, coords = vector3(1841.2963, 3681.1711, 34.1892), width = 3, length = 3, cameraLocation = vector4(1839.7710, 3680.2510, 34.1892, 300.7488)},
    [8] = {requiredJob = 'sasp', isGang = false, coords = vector3(1841.2963, 3681.1711, 34.1892), width = 3, length = 3, cameraLocation = vector4(1839.7710, 3680.2510, 34.1892, 300.7488)},
    
    [9] = {requiredJob = 'lspd', isGang = false, coords = vector3(-444.2002, 6018.0752, 36.9957), width = 3, length = 3, cameraLocation = vector4(-445.5872, 6016.7744, 36.9957, 313.7904)}, -- Paleto
    [10] = {requiredJob = 'bcso', isGang = false, coords = vector3(-444.2002, 6018.0752, 36.9957), width = 3, length = 3, cameraLocation = vector4(-445.5872, 6016.7744, 36.9957, 313.7904)},
    [11] = {requiredJob = 'sasp', isGang = false, coords = vector3(-444.2002, 6018.0752, 36.9957), width = 3, length = 3, cameraLocation = vector4(-445.5872, 6016.7744, 36.9957, 313.7904)},
}
```

**Comment by Lavarris** [comment]
Simply add the following line under line #540.

local clothingRoom = Config.ClothingRooms[tonumber(string.sub(zoneName, 15))]

**Comment by uShifty** [comment]
This was already fixed in PR #109

**Comment by ADRNALN** [comment]
That PR did not fix it, now the draw text doesn't even show up when in a zone for example like mission row

**Comment by uShifty** [comment]
> That PR did not fix it, now the draw text doesn't even show up when in a zone for example like mission row

Just downloaded it from the main branch and it works just fine, provide the new error as the line would have changed

**Comment by ADRNALN** [comment]
No errors this time
